### PR TITLE
Fix the min PHP version

### PR DESCRIPTION
**Pull request by stof**
namespaces are used, so PHP 5.2 is not supported

### CODE REVIEW

**Comment by lyrixx** [comment]
The pure php probe works on PHP 5.2

**Comment by stof** [comment]
even the probe does not (see my comment in #4.

**Comment by romainneutron** [comment]
@stof could we close this one now?

**Comment by nicolas-grekas** [comment]
We could remove the require section entirely, what do you think?

**Comment by stof** [comment]
well, stating the min PHP version required by the package is a good idea IMO

**Pull request closed without merging**
