### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by pgrimaud**

### CODE REVIEW

**Comment by lolautruche** [comment]
Thanks @pgrimaud !

**Comment by GrahamCampbell** [comment]
This repo is marked as read-only. Is the upstream one not open source, since I can't find it?

**Comment by lolautruche** [comment]
@GrahamCampbell the upstream repo is indeed not open-source. We forward the community PRs to it 😃

**Comment by GrahamCampbell** [comment]
Ah, I see. :P

**Comment by romainneutron** [comment]
Thanks, merged as of 709bc75b6dc9a5435a2cdc7517246d6d3b16ec1c

**Pull request closed without merging**
